services:
  backend:
    build: 
      context: ./CentralDasImagens
      dockerfile: Dockerfile
    container_name: backend-CentralDasImagens
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: CentralDasImagens
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/central
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql-db-CentralDasImagens
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: central
      MYSQL_USER: senac
      MYSQL_PASSWORD: senac
    ports: 
      - "4306:3306"
    volumes:
      - mysql-db-CentralDasImagens:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
  frontend:
    build: ./central-das-imagens-front
    ports:
      - "3000:80"
    depends_on:
      - backend
      - db
volumes:
  mysql-db-CentralDasImagens: